DROP FUNCTION IF EXISTS `DISTANCE`
CREATE FUNCTION `DISTANCE`(origLat FLOAT, origLon FLOAT, destLat FLOAT, destLon FLOAT) RETURNS FLOAT RETURN 6366 * ACOS(COS(RADIANS(origLat)) * COS(RADIANS(destLat)) * COS(RADIANS(destLon) - RADIANS(origLon)) + SIN(RADIANS(origLat)) * SIN(RADIANS(destLat)))
