<?php

//define('name', "value");

/**
 * Implements hook_theme().
 * Permet de définir de nouveaux templates pour le théme arpavie
 */
function arpavie_core_theme($existing, $type, $theme, $path)
{
    return [
        'edit_pass_user' => [
            'template' => 'edit_pass_user',
            'variables' => ['user' => null, 'pass_token' => null],
        ]
    ];
}

/**
 * Implements hook_preprocess_node().
 * Surcharge du hook node pour personnaliser l'affichage des pages par défaut
 */
function arpavie_core_preprocess_node(&$variables)
{

    $node = $variables['elements']['#node'];
    $variables['base_path'] = base_path();
    switch ($node->getType()) {
       
    }
}

/**
 * Implements hook_preprocess().
 *
 * Permet d'injecter des données/librairies pour le hook page
 */
function arpavie_core_preprocess_page(&$variables)
{

}



/**
 * Implements hook_module_form_alter()
 * Permert de modifier la définition des formulaires indentifiés par $form_id
 */
function arpavie_core_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{

        switch ($form_id) {
            
            case "user_pass":
 
                break;

            case "user_pass_reset":
                break;


        }
    
}


/**
 * Surchage le hook d'envoi de mail
 * Implements hook_mail().
 */
function arpavie_core_mail($key, &$message, $params)
{

}
